name: Build and Release Resume

on:
  push:
    branches:
      - trunk

jobs:
  build_latex_and_release:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: ahad-resume-2025.tex
      - name: Generate shared timestamp
        id: meta
        run: |
          TIMESTAMP=$(TZ="Australia/Sydney" date +"%Y.%m.%d.%H%M")
          echo "release_tag=$TIMESTAMP" >> "$GITHUB_OUTPUT"
          echo "pdf_name=ahad-resume-$TIMESTAMP.pdf" >> "$GITHUB_OUTPUT"
      - name: Rename compiled PDF
        run: |
          mv ahad-resume-2025.pdf "${{ steps.meta.outputs.pdf_name }}"
      - name: Release PDF file
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.meta.outputs.release_tag }}
          files: ${{ steps.meta.outputs.pdf_name }}
      - name: Update address for link shortener
        run: |
          curl -X POST "${{ secrets.PIASH_ADDRESS }}" \
            -u "${{ secrets.PIASH_USERNAME }}:${{ secrets.PIASH_PASSWORD }}" \
            -H "Content-Type: application/json" \
            -d '{
              "key": "resume",
              "url": "https://github.com/maacpiash/static/releases/download/${{ steps.meta.outputs.release_tag }}/${{ steps.meta.outputs.pdf_name }}"
            }'
