name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: ahad-resume-2024.tex
      - name: Generate a release tag
        id: tag
        run: echo "::set-output name=release_tag::$(date +"%Y.%m.%d")"
      - name: Release PDF file
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tag.outputs.release_tag }}
          files: ahad-resume-2024.pdf
